Repository rancher/harvester-cloud, pull requests merged in 2025-02, with the labels that each got.

#9 Modified DEMO 2 from README.md file
  images/GCP_PROJ_README_10.png
  projects/google-cloud/README.md
Labels: documentation

#11 Added DNS name to Harvester URL output
  projects/google-cloud/outputs.tf
Labels: enhancement

#12 Added a first version of GH action to test the code before PRs approval
  .github/workflows/ci.yaml
Labels: enhancement

#19 Feature/azure project
  .github/workflows/ci.yaml
  .gitignore
  images/AZURE_PROJ_README_1.png
  images/AZURE_PROJ_README_10.png
  images/AZURE_PROJ_README_11.png
  images/AZURE_PROJ_README_12.png
  images/AZURE_PROJ_README_2.png
  images/AZURE_PROJ_README_3.png
  images/AZURE_PROJ_README_4.png
  images/AZURE_PROJ_README_5.png
  images/AZURE_PROJ_README_6.png
  images/AZURE_PROJ_README_7.png
  images/AZURE_PROJ_README_8.png
  images/AZURE_PROJ_README_9.png
  modules/azure/README.md
  modules/azure/virtual-machine/docs.md
  modules/azure/virtual-machine/main.tf
  modules/azure/virtual-machine/outputs.tf
  modules/azure/virtual-machine/variables.tf
  projects/azure/README.md
  projects/azure/docs.md
  projects/azure/main.tf
  projects/azure/outputs.tf
  projects/azure/providers.tf
  projects/azure/terraform.tfvars.example
  projects/azure/variables.tf
Labels: documentation, enhancement

#22 Performed GCP code review
  modules/google-cloud/compute-engine/docs.md
  modules/google-cloud/compute-engine/main.tf
  modules/google-cloud/compute-engine/variables.tf
  projects/google-cloud/main.tf
  projects/google-cloud/providers.tf
Labels: documentation, enhancement, good first issue

#23 Fixed Azure GH Actions
  .github/workflows/ci.yaml
Labels: bug

#24 Feature/infrastructure estimation costs
  docs/INFRASTRUCTURE_ESTIMATE_COST.md
Labels: documentation
