Repository rancher/harvester-cloud, pull requests merged in 2025-03, with the labels that each got.

#31 Removed hardcoded value for ssh_username variable from network-creation project
  projects/harvester-ops/network-creation/docs.md
  projects/harvester-ops/network-creation/main.tf
  projects/harvester-ops/network-creation/terraform.tfvars.example
  projects/harvester-ops/network-creation/variables.tf
Labels: bug

#26 Added HARVESTER_DEPLOYMENT_PROCESS.md doc file
  docs/HARVESTER_DEPLOYMENT_PROCESS.md
  images/HARVESTER_DEPLOYMENT_PROCESS_1.png
  images/HARVESTER_DEPLOYMENT_PROCESS_2.png
  images/HARVESTER_DEPLOYMENT_PROCESS_3.png
  images/HARVESTER_DEPLOYMENT_PROCESS_4.png
  images/HARVESTER_DEPLOYMENT_PROCESS_5.png
  images/HARVESTER_DEPLOYMENT_PROCESS_6.png
Labels: documentation

#17 Analyzed and documented the performance of the Harvester cluster running on a Google Cloud virtual machine
  docs/PERFORMANCE.md
  images/PERFORMANCE_1.png
  images/PERFORMANCE_2.png
  images/PERFORMANCE_3.png
  images/PERFORMANCE_4.png
  images/PERFORMANCE_5.png
  images/PERFORMANCE_6.png
  images/PERFORMANCE_7.png
  images/PERFORMANCE_8.png
Labels: documentation

#40 Modified the principal README.md file
  README.md
Labels: documentation

#42 Feature/issue 41
  projects/azure/docs.md
  projects/azure/terraform.tfvars.example
  projects/azure/variables.tf
  projects/digitalocean/docs.md
  projects/digitalocean/terraform.tfvars.example
  projects/digitalocean/variables.tf
  projects/google-cloud/docs.md
  projects/google-cloud/terraform.tfvars.example
  projects/google-cloud/variables.tf
Labels: enhancement

#46 Fix typos in `README.md`
  projects/azure/README.md
  projects/google-cloud/README.md
  projects/harvester-ops/image-creation/README.md
  projects/harvester-ops/network-creation/README.md
  projects/harvester-ops/vm-pool-creation/README.md
Labels: bug, documentation

#47 Modified README.md files for Google and Azure environments regarding Intel processor compatibility.
  projects/azure/README.md
  projects/google-cloud/README.md
Labels: documentation
