Repository rancher/harvester-cloud, pull requests merged in 2025-04, with the labels that each got.

#52 Modifying harvester_startup_script_sh.tpl and Terraform projects to a…
  modules/harvester/deployment-script/harvester_startup_script_sh.tpl
  projects/azure/main.tf
  projects/digitalocean/main.tf
  projects/google-cloud/main.tf
Labels: enhancement

#57 Created logic to add more data disks to nested Harvester VMs
  docs/HARVESTER_DEPLOYMENT_PROCESS.md
  images/AZURE_PROJ_README_13.png
  images/AZURE_PROJ_README_14.png
  images/AZURE_PROJ_README_15.png
  images/AZURE_PROJ_README_16.png
  images/AZURE_PROJ_README_17.png
  images/DO_PROJ_README_13.png
  images/DO_PROJ_README_14.png
  images/DO_PROJ_README_15.png
  images/DO_PROJ_README_16.png
  images/DO_PROJ_README_17.png
  images/GCP_PROJ_README_13.png
  images/GCP_PROJ_README_14.png
  images/GCP_PROJ_README_15.png
  images/GCP_PROJ_README_16.png
  images/GCP_PROJ_README_17.png
  modules/azure/virtual-machine/docs.md
  modules/azure/virtual-machine/variables.tf
  modules/digitalocean/droplet/docs.md
  modules/digitalocean/droplet/variables.tf
  modules/google-cloud/compute-engine/docs.md
  modules/google-cloud/compute-engine/variables.tf
  modules/harvester/deployment-script/harvester_startup_script_sh.tpl
  projects/azure/README.md
  projects/azure/docs.md
  projects/azure/main.tf
  projects/azure/terraform.tfvars.example
  projects/azure/variables.tf
  projects/digitalocean/README.md
  projects/digitalocean/docs.md
  projects/digitalocean/main.tf
  projects/digitalocean/terraform.tfvars.example
  projects/digitalocean/variables.tf
  projects/google-cloud/README.md
  projects/google-cloud/docs.md
  projects/google-cloud/main.tf
  projects/google-cloud/terraform.tfvars.example
  projects/google-cloud/variables.tf
Labels: documentation, enhancement

#60 2025/Q2 Review - Updated several Terraform providers and brought the default Harvester version to 1.5.0
  projects/azure/docs.md
  projects/azure/providers.tf
  projects/azure/terraform.tfvars.example
  projects/azure/variables.tf
  projects/digitalocean/docs.md
  projects/digitalocean/providers.tf
  projects/digitalocean/terraform.tfvars.example
  projects/digitalocean/variables.tf
  projects/google-cloud/docs.md
  projects/google-cloud/providers.tf
  projects/google-cloud/terraform.tfvars.example
  projects/google-cloud/variables.tf
Labels: good first issue
